### ISSUE TITLE
project layout is not Luarocks friendly

### ISSUE THREAD

**Issue by fperrad** [kmarkus/lsdbus#4]
see https://github.com/luarocks/luarocks/issues/1554

what do you think about the following layout ?
```
src/c/*.[ch]
src/lua/*.lua
```

**Comment by kmarkus** [comment]
It would be OK for me, if it helps with the packaging.

**Comment by kmarkus** [comment]
Not sure I like the mix. But how about keeping `src/` as is with the `*.c` files, but moving `lua/` to `src/lua/` ?
